### ISSUE TITLE
Dokumentation

### ISSUE THREAD

**Issue by omuellersch** [slashworks/contao-trackingmanager-bundle#1]
Zufällig bin auf Eure Erweiterung gestoßen und habe gesehen, dass es Sie auch im ContaoManager verfügbar ist. Gibt es auch eine Dokumentation dazu? Thx

**Comment by Stefanmelz** [comment]
Hey. Aktuell steht alles im Code in den Kommentaren. Bei Gelegenheit erstelle ich mal eine Doku. Vielleicht heute schon.

**Comment by Stefanmelz** [comment]
Done. Gib gern mal Rückmeldung ob du mit der Beschreibung klar gekommen bist.
